# -*- coding: utf-8 -*-
"""Image Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pCqwQ-XQPcSvn_gvx7V2xIOtCoV6-eTD
"""

import cv2
import numpy as np
import pandas as pd
from google.colab import files

# Upload video file
print("Please upload your video file:")
uploaded = files.upload()

# Get the uploaded file name
video_path = list(uploaded.keys())[0]

def process_video_for_squares(video_path, fps=5):
    """Process video to detect squares and output their centroids, z-coordinate, and rotation angles."""
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("Error: Could not open video.")
        return

    # Get video properties
    video_fps = cap.get(cv2.CAP_PROP_FPS)
    frame_skip = int(video_fps / fps)  # Determine frames to skip for desired FPS

    frame_count = 0
    results = []  # Store the results for all frames

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Process only frames at the specified rate
        if frame_count % frame_skip == 0:
            # Convert frame to grayscale
            gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

            # Apply Gaussian Blur to reduce noise
            blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

            # Apply binary thresholding
            _, binary_frame = cv2.threshold(blurred_frame, 100, 255, cv2.THRESH_BINARY)

            # Find contours
            contours, _ = cv2.findContours(binary_frame, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            print(f"Frame {frame_count}: Detected {len(contours)} contours.")

            for contour in contours:
                # Approximate contour to a polygon
                epsilon = 0.04 * cv2.arcLength(contour, True)
                approx = cv2.approxPolyDP(contour, epsilon, True)

                # Check if the polygon is a square (4 sides and convex)
                if len(approx) == 4 and cv2.isContourConvex(approx):
                    area = cv2.contourArea(contour)
                    print(f"Frame {frame_count}: Detected square with area {area}.")
                    if 500 < area < 10000:  # Relaxed area filter
                        # Calculate centroid
                        moments = cv2.moments(contour)
                        if moments["m00"] == 0:
                            continue
                        cx = int(moments["m10"] / moments["m00"])
                        cy = int(moments["m01"] / moments["m00"])

                        # Estimate z-coordinate (placeholder logic)
                        z = 1 / np.sqrt(area) if area > 0 else 0

                        # Calculate rotation angle
                        rect = cv2.minAreaRect(contour)
                        box = cv2.boxPoints(rect)
                        box = np.int0(box)
                        top_right = sorted(box, key=lambda p: (p[0], -p[1]))[-1]
                        angle = np.degrees(np.arctan2(cy - top_right[1], top_right[0] - cx))

                        # Append results to the list
                        results.append({"Frame": frame_count, "x": cx, "y": cy, "z": z, "θ": angle})

        frame_count += 1

    cap.release()

    # Convert results to a DataFrame and display
    if results:
        df = pd.DataFrame(results)
        print("\nFinal Results (x, y, z, θ for each frame):")
        print(df)
    else:
        print("No valid squares detected in the video.")
    return results

# Process the uploaded video and store results
results_df = process_video_for_squares(video_path)

import cv2
import numpy as np
import pandas as pd
from google.colab import files

# Upload video file
print("Please upload your video file:")
uploaded = files.upload()

# Get the uploaded file name
video_path = list(uploaded.keys())[0]

def process_video_for_squares(video_path, fps=5):
    """Process video to detect squares and output their centroids, z-coordinate, and rotation angles."""
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("Error: Could not open video.")
        return

    # Get video properties
    video_fps = cap.get(cv2.CAP_PROP_FPS)
    frame_skip = int(video_fps / fps)  # Determine frames to skip for desired FPS

    frame_count = 0
    results = []  # Store the results for all frames

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Process only frames at the specified rate
        if frame_count % frame_skip == 0:
            # Convert frame to HSV color space for better background segmentation
            hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

            # Define tan background color range (adjust based on your video)
            lower_tan = np.array([10, 50, 50])  # Lower HSV for tan
            upper_tan = np.array([30, 255, 255])  # Upper HSV for tan

            # Create a mask for the tan background
            tan_mask = cv2.inRange(hsv_frame, lower_tan, upper_tan)

            # Invert the mask to highlight the black square
            black_square_mask = cv2.bitwise_not(tan_mask)

            # Apply Gaussian Blur to reduce noise
            blurred_frame = cv2.GaussianBlur(black_square_mask, (5, 5), 0)

            # Use adaptive thresholding for binary conversion
            binary_frame = cv2.adaptiveThreshold(
                blurred_frame, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2
            )

            # Find contours
            contours, _ = cv2.findContours(binary_frame, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

            for contour in contours:
                # Approximate contour to a polygon
                epsilon = 0.04 * cv2.arcLength(contour, True)
                approx = cv2.approxPolyDP(contour, epsilon, True)

                # Check if the polygon is a square (4 sides and convex)
                if len(approx) == 4 and cv2.isContourConvex(approx):
                    area = cv2.contourArea(contour)
                    if 500 < area < 15000:  # Adjusted area range for black square
                        # Calculate centroid
                        moments = cv2.moments(contour)
                        if moments["m00"] == 0:
                            continue
                        cx = int(moments["m10"] / moments["m00"])
                        cy = int(moments["m01"] / moments["m00"])

                        # Estimate z-coordinate (placeholder logic)
                        z = 1 / np.sqrt(area) if area > 0 else 0

                        # Calculate rotation angle
                        rect = cv2.minAreaRect(contour)
                        box = cv2.boxPoints(rect)
                        box = np.int0(box)
                        top_right = sorted(box, key=lambda p: (p[0], -p[1]))[-1]
                        angle = np.degrees(np.arctan2(cy - top_right[1], top_right[0] - cx))

                        # Append results to the list
                        results.append({"Frame": frame_count, "x": cx, "y": cy, "z": z, "θ": angle})

        frame_count += 1

    cap.release()

    # Convert results to a DataFrame and display
    if results:
        df = pd.DataFrame(results)
        print("\nFinal Results (x, y, z, θ for each frame):")
        print(df)
    else:
        print("No valid squares detected in the video.")
    return results

# Process the uploaded video and store results
results_df = process_video_for_squares(video_path)
#for black square on tan background -

import cv2
import numpy as np
from google.colab import files
import os
from google.colab.patches import cv2_imshow


# Upload video file
print("Please upload your video file:")
uploaded = files.upload()

# Get the uploaded file name
video_path = list(uploaded.keys())[0]


def process_video_for_circles(video_path, fps=5):
    """Process video to detect circles and output their centroids, radii, and depth."""
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("Error: Could not open video.")
        return

    # Get video properties
    video_fps = cap.get(cv2.CAP_PROP_FPS)
    frame_skip = int(video_fps / fps)  # Determine frames to skip for desired FPS

    frame_count = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Process only frames at the specified rate
        if frame_count % frame_skip == 0:
            # Convert frame to grayscale
            gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

            # Apply Gaussian Blur to reduce noise
            blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

            # Detect circles using Hough Circle Transform
            circles = cv2.HoughCircles(
                blurred_frame,
                cv2.HOUGH_GRADIENT,
                dp=1.2,  # Inverse ratio of the accumulator resolution to the image resolution
                minDist=50,  # Minimum distance between circle centers
                param1=50,  # Upper threshold for Canny edge detection
                param2=30,  # Threshold for center detection
                minRadius=10,  # Minimum circle radius
                maxRadius=100  # Maximum circle radius
            )

            if circles is not None:
                circles = np.round(circles[0, :]).astype("int")  # Round and convert to integer
                for (x, y, r) in circles:
                    # Placeholder logic for z-coordinate based on radius
                    z = 1 / r if r != 0 else 0  # Replace with actual depth calculation if available

                    # Print circle information
                    print(f"Frame {frame_count}: x={x}, y={y}, radius={r}, z={z:.2f}")

                    # Draw the circle and centroid on the frame
                    cv2.circle(frame, (x, y), r, (0, 255, 0), 2)  # Circle
                    cv2.circle(frame, (x, y), 5, (255, 0, 0), -1)  # Centroid
                    cv2.putText(frame, f"x={x}, y={y}, r={r}, z={z:.2f}",
                                (x - 50, y - r - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

            # Save and display the processed frame
            frame_output_path = f"processed_frame_{frame_count}.jpg"
            cv2.imwrite(frame_output_path, frame)
            cv2_imshow(frame)  # Use cv2_imshow to display the frame in Colab

        frame_count += 1

    cap.release()
    cv2.destroyAllWindows()

# Process the uploaded video
process_video_for_circles(video_path)

import cv2
import numpy as np
from google.colab import files
import os

# Define pixel-to-mm scale
mm_per_pixel = 0.1  # Example: 1 pixel = 0.1 mm

# Upload video file
print("Please upload your video file:")
uploaded = files.upload()

# Get the uploaded file name
video_path = list(uploaded.keys())[0]

def process_video_for_circles(video_path, fps=5):
    """Process video to detect circles and output their centroids, radii, and depth."""
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("Error: Could not open video.")
        return

    # Get video properties
    video_fps = cap.get(cv2.CAP_PROP_FPS)
    frame_width = cap.get(cv2.CAP_PROP_FRAME_WIDTH)  # Retrieve width of the frame
    frame_height = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)  # Retrieve height of the frame

    # Convert frame dimensions to millimeters
    frame_width_mm = frame_width * mm_per_pixel
    frame_height_mm = frame_height * mm_per_pixel
    print(f"Frame Dimensions (mm): Width={frame_width_mm:.2f} mm, Height={frame_height_mm:.2f} mm")

    frame_skip = int(video_fps / fps)  # Determine frames to skip for desired FPS
    frame_count = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Process only frames at the specified rate
        if frame_count % frame_skip == 0:
            # Convert frame to grayscale
            gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

            # Apply Gaussian Blur to reduce noise
            blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

            # Detect circles using Hough Circle Transform
            circles = cv2.HoughCircles(
                blurred_frame,
                cv2.HOUGH_GRADIENT,
                dp=1.2,  # Inverse ratio of the accumulator resolution to the image resolution
                minDist=50,  # Minimum distance between circle centers
                param1=50,  # Upper threshold for Canny edge detection
                param2=30,  # Threshold for center detection
                minRadius=10,  # Minimum circle radius
                maxRadius=100  # Maximum circle radius
            )

            if circles is not None:
                circles = np.round(circles[0, :]).astype("int")  # Round and convert to integer
                for (x, y, r) in circles:
                    # Convert coordinates and radius to millimeters
                    x_mm = x * mm_per_pixel
                    y_mm = y * mm_per_pixel
                    r_mm = r * mm_per_pixel
                    z_mm = 1 / r_mm if r_mm != 0 else 0  # Placeholder depth calculation

                    # Print circle information
                    print(f"Frame {frame_count}: x={x_mm:.2f} mm, y={y_mm:.2f} mm, radius={r_mm:.2f} mm, z={z_mm:.2f} mm")

                    # Draw the circle and centroid on the frame
                    cv2.circle(frame, (x, y), r, (0, 255, 0), 2)  # Circle
                    cv2.circle(frame, (x, y), 5, (255, 0, 0), -1)  # Centroid
                    cv2.putText(frame, f"x={x_mm:.2f} mm, y={y_mm:.2f} mm, r={r_mm:.2f} mm, z={z_mm:.2f} mm",
                                (x - 50, y - r - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

            # Save the processed frame
            frame_output_path = f"processed_frame_{frame_count}.jpg"
            cv2.imwrite(frame_output_path, frame)
            cv2_imshow(frame)  # Use cv2_imshow to display the frame in Colab

        frame_count += 1

    cap.release()
    cv2.destroyAllWindows()

# Process the uploaded video
process_video_for_circles(video_path)

import cv2
import numpy as np
from google.colab import files
import os

# Define pixel-to-mm scale
mm_per_pixel = 0.1  # Example: 1 pixel = 0.1 mm

# Upload video file
print("Please upload your video file:")
uploaded = files.upload()

# Get the uploaded file name
video_path = list(uploaded.keys())[0]

def process_video_for_circles(video_path, fps=5):
    """Process video to detect circles and output their centroids, radii, and depth."""
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("Error: Could not open video.")
        return

    # Get video properties
    video_fps = cap.get(cv2.CAP_PROP_FPS)
    frame_width = cap.get(cv2.CAP_PROP_FRAME_WIDTH)  # Retrieve width of the frame
    frame_height = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)  # Retrieve height of the frame

    # Convert frame dimensions to millimeters
    frame_width_mm = frame_width * mm_per_pixel
    frame_height_mm = frame_height * mm_per_pixel
    print(f"Frame Dimensions (mm): Width={frame_width_mm:.2f} mm, Height={frame_height_mm:.2f} mm")

    frame_skip = int(video_fps / fps)  # Determine frames to skip for desired FPS
    frame_count = 0

    stationary_objects = []  # To store final stationary x, y, z, and radius values

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Process only frames at the specified rate
        if frame_count % frame_skip == 0:
            # Convert frame to grayscale
            gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

            # Apply Gaussian Blur to reduce noise
            blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

            # Detect circles using Hough Circle Transform
            circles = cv2.HoughCircles(
                blurred_frame,
                cv2.HOUGH_GRADIENT,
                dp=1.2,  # Inverse ratio of the accumulator resolution to the image resolution
                minDist=50,  # Minimum distance between circle centers
                param1=50,  # Upper threshold for Canny edge detection
                param2=30,  # Threshold for center detection
                minRadius=10,  # Minimum circle radius
                maxRadius=100  # Maximum circle radius
            )

            if circles is not None:
                circles = np.round(circles[0, :]).astype("int")  # Round and convert to integer
                for (x, y, r) in circles:
                    # Convert coordinates and radius to millimeters
                    x_mm = x * mm_per_pixel
                    y_mm = y * mm_per_pixel
                    r_mm = r * mm_per_pixel
                    z_mm = 75  # Set z to 75 mm for stationary objects

                    # Print circle information
                    print(f"Frame {frame_count}: x={x_mm:.2f} mm, y={y_mm:.2f} mm, radius={r_mm:.2f} mm, z={z_mm:.2f} mm")

                    # Store stationary object details
                    stationary_objects.append(f"x={x_mm:.2f}, y={y_mm:.2f}, z={z_mm:.2f}, radius={r_mm:.2f}")

                    # Draw the circle and centroid on the frame
                    cv2.circle(frame, (x, y), r, (0, 255, 0), 2)  # Circle
                    cv2.circle(frame, (x, y), 5, (255, 0, 0), -1)  # Centroid
                    cv2.putText(frame, f"x={x_mm:.2f} mm, y={y_mm:.2f} mm, r={r_mm:.2f} mm, z={z_mm:.2f} mm",
                                (x - 50, y - r - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

            # Save the processed frame
            frame_output_path = f"processed_frame_{frame_count}.jpg"
            cv2.imwrite(frame_output_path, frame)
            cv2_imshow(frame)  # Use cv2_imshow to display the frame in Colab

        frame_count += 1

    # Write stationary object details to a text file
    with open("stationary_objects.txt", "w") as file:
        file.write("\n".join(stationary_objects))
        print("Stationary object details exported to stationary_objects.txt")

    cap.release()
    cv2.destroyAllWindows()

# Process the uploaded video
process_video_for_circles(video_path)

import cv2
import numpy as np
import time

# Define pixel-to-mm scale
mm_per_pixel = 0.1  # Example: 1 pixel = 0.1 mm

def process_webcam_for_circles(fps_interval=5):
    """
    Process webcam input to detect circles and output their centroids, radii, and depth.
    Only analyze one frame every `fps_interval` seconds.
    """
    # Open the webcam
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("Error: Could not access the webcam.")
        return

    stationary_objects = []  # To store stationary x, y, z, and radius values
    last_detected = None  # Store the previous frame's detected circles

    print("Press 'q' to quit.")

    while True:
        start_time = time.time()
        ret, frame = cap.read()
        if not ret:
            print("Error: Could not read frame from the webcam.")
            break

        # Convert frame to grayscale
        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # Apply Gaussian Blur to reduce noise
        blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

        # Detect circles using Hough Circle Transform
        circles = cv2.HoughCircles(
            blurred_frame,
            cv2.HOUGH_GRADIENT,
            dp=1.2,  # Inverse ratio of the accumulator resolution to the image resolution
            minDist=50,  # Minimum distance between circle centers
            param1=50,  # Upper threshold for Canny edge detection
            param2=30,  # Threshold for center detection
            minRadius=10,  # Minimum circle radius
            maxRadius=100  # Maximum circle radius
        )

        if circles is not None:
            circles = np.round(circles[0, :]).astype("int")  # Round and convert to integer
            for (x, y, r) in circles:
                # Convert coordinates and radius to millimeters
                x_mm = x * mm_per_pixel
                y_mm = y * mm_per_pixel
                r_mm = r * mm_per_pixel
                z_mm = 75  # Set z to 75 mm for stationary objects

                # Check if the object is stationary (detected in two consecutive frames)
                if last_detected is not None:
                    for (prev_x, prev_y, prev_r) in last_detected:
                        if abs(prev_x - x) < 5 and abs(prev_y - y) < 5 and abs(prev_r - r) < 5:
                            # Object considered stationary
                            stationary_objects.append(f"x={x_mm:.2f}, y={y_mm:.2f}, z={z_mm:.2f}, radius={r_mm:.2f}")
                            print(f"Stationary Object: x={x_mm:.2f} mm, y={y_mm:.2f} mm, z={z_mm:.2f} mm, radius={r_mm:.2f}")

                # Draw the circle and centroid on the frame
                cv2.circle(frame, (x, y), r, (0, 255, 0), 2)  # Circle
                cv2.circle(frame, (x, y), 5, (255, 0, 0), -1)  # Centroid
                cv2.putText(frame, f"x={x_mm:.2f} mm, y={y_mm:.2f} mm, r={r_mm:.2f} mm, z={z_mm:.2f} mm",
                            (x - 50, y - r - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

            # Update last detected circles
            last_detected = circles

        # Display the frame with detected circles
        cv2.imshow("Webcam Circle Detection", frame)

        # Break loop on 'q' key press
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

        # Wait for the next frame interval
        time_elapsed = time.time() - start_time
        time.sleep(max(0, fps_interval - time_elapsed))

    # Write stationary object details to a text file
    with open("stationary_objects.txt", "w") as file:
        file.write("\n".join(stationary_objects))
        print("Stationary object details exported to stationary_objects.txt")

    cap.release()
    cv2.destroyAllWindows()

# Run the webcam processing function
process_webcam_for_circles()

import cv2
import numpy as np
import time

# Define pixel-to-mm scale
mm_per_pixel = 0.1  # Example: 1 pixel = 0.1 mm

def process_usb_webcam_for_circles(camera_index=0, fps_interval=5):
    """
    Process USB webcam input to detect circles and output their centroids, radii, and depth.
    Only analyze one frame every `fps_interval` seconds.
    """
    # Open the USB webcam using the specified camera index (port from device manager)
    cap = cv2.VideoCapture(camera_index, cv2.CAP_DSHOW)
    if not cap.isOpened():
        print(f"Error: Could not access the webcam on port {camera_index}.")
        return

    stationary_objects = []  # To store stationary x, y, z, and radius values
    last_detected = None  # Store the previous frame's detected circles

    print("Press 'q' to quit.")

    while True:
        start_time = time.time()
        ret, frame = cap.read()
        if not ret:
            print("Error: Could not read frame from the webcam.")
            break

        # Convert frame to grayscale
        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # Apply Gaussian Blur to reduce noise
        blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

        # Detect circles using Hough Circle Transform
        circles = cv2.HoughCircles(
            blurred_frame,
            cv2.HOUGH_GRADIENT,
            dp=1.2,  # Inverse ratio of the accumulator resolution to the image resolution
            minDist=50,  # Minimum distance between circle centers
            param1=50,  # Upper threshold for Canny edge detection
            param2=30,  # Threshold for center detection
            minRadius=10,  # Minimum circle radius
            maxRadius=100  # Maximum circle radius
        )

        if circles is not None:
            circles = np.round(circles[0, :]).astype("int")  # Round and convert to integer
            for (x, y, r) in circles:
                # Convert coordinates and radius to millimeters
                x_mm = x * mm_per_pixel
                y_mm = y * mm_per_pixel
                r_mm = r * mm_per_pixel
                z_mm = 75  # Set z to 75 mm for stationary objects

                # Check if the object is stationary (detected in two consecutive frames)
                if last_detected is not None:
                    for (prev_x, prev_y, prev_r) in last_detected:
                        if abs(prev_x - x) < 5 and abs(prev_y - y) < 5 and abs(prev_r - r) < 5:
                            # Object considered stationary
                            stationary_objects.append(f"x={x_mm:.2f}, y={y_mm:.2f}, z={z_mm:.2f}, radius={r_mm:.2f}")
                            print(f"Stationary Object: x={x_mm:.2f} mm, y={y_mm:.2f} mm, z={z_mm:.2f} mm, radius={r_mm:.2f}")

                # Draw the circle and centroid on the frame
                cv2.circle(frame, (x, y), r, (0, 255, 0), 2)  # Circle
                cv2.circle(frame, (x, y), 5, (255, 0, 0), -1)  # Centroid
                cv2.putText(frame, f"x={x_mm:.2f} mm, y={y_mm:.2f} mm, r={r_mm:.2f} mm, z={z_mm:.2f} mm",
                            (x - 50, y - r - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

            # Update last detected circles
            last_detected = circles

        # Display the frame with detected circles
        cv2.imshow("USB Webcam Circle Detection", frame)

        # Break loop on 'q' key press
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

        # Wait for the next frame interval
        time_elapsed = time.time() - start_time
        time.sleep(max(0, fps_interval - time_elapsed))

    # Write stationary object details to a text file
    with open("stationary_objects.txt", "w") as file:
        file.write("\n".join(stationary_objects))
        print("Stationary object details exported to stationary_objects.txt")

    cap.release()
    cv2.destroyAllWindows()

# Run the USB webcam processing function
# Use the correct camera index from Device Manager (e.g., 0, 1, 2, etc.)
process_usb_webcam_for_circles(camera_index=0)

import cv2

# Test camera indices
for i in range(5):  # Check indexes 0 to 4
    cap = cv2.VideoCapture(i)
    if cap.isOpened():
        print(f"Camera found at index {i}")
        cap.release()
    else:
        print(f"No camera found at index {i}")

import cv2
import numpy as np
import time
import os

# Define pixel-to-mm scale
mm_per_pixel = 0.1  # Example: 1 pixel = 0.1 mm

def process_usb_webcam_for_circles(camera_index=0, fps_interval=5):
    """
    Process USB webcam input to detect circles and output their centroids, radii, and depth.
    Only analyze one frame every `fps_interval` seconds.
    """
    # Open the USB webcam using the specified camera index (port from device manager)
    cap = cv2.VideoCapture(camera_index, cv2.CAP_DSHOW)
    if not cap.isOpened():
        print(f"Error: Could not access the webcam on port {camera_index}.")
        return

    stationary_objects = []  # To store stationary x, y, z, and radius values
    last_detected = None  # Store the previous frame's detected circles
    last_written_location = None  # Track the last written constant location

    print("Press 'q' to quit.")

    while True:
        start_time = time.time()
        ret, frame = cap.read()
        if not ret:
            print("Error: Could not read frame from the webcam.")
            break

        # Convert frame to grayscale
        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # Apply Gaussian Blur to reduce noise
        blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

        # Detect circles using Hough Circle Transform
        circles = cv2.HoughCircles(
            blurred_frame,
            cv2.HOUGH_GRADIENT,
            dp=1.2,  # Inverse ratio of the accumulator resolution to the image resolution
            minDist=50,  # Minimum distance between circle centers
            param1=50,  # Upper threshold for Canny edge detection
            param2=30,  # Threshold for center detection
            minRadius=10,  # Minimum circle radius
            maxRadius=100  # Maximum circle radius
        )

        if circles is not None:
            circles = np.round(circles[0, :]).astype("int")  # Round and convert to integer
            for (x, y, r) in circles:
                # Convert coordinates and radius to millimeters
                x_mm = x * mm_per_pixel
                y_mm = y * mm_per_pixel
                r_mm = r * mm_per_pixel
                z_mm = 75  # Set z to 75 mm for stationary objects

                # Check if the object is stationary (detected in two consecutive frames)
                if last_detected is not None:
                    for (prev_x, prev_y, prev_r) in last_detected:
                        if abs(prev_x - x) < 5 and abs(prev_y - y) < 5 and abs(prev_r - r) < 5:
                            # Object considered stationary
                            location_line = f"x={x_mm:.2f}, y={y_mm:.2f}, z={z_mm:.2f}, radius={r_mm:.2f}"
                            if location_line != last_written_location:  # Only write if location is different
                                stationary_objects.append(location_line)
                                last_written_location = location_line  # Update the last written location
                                print(f"Stationary Object: {location_line}")

                # Draw the circle and centroid on the frame
                cv2.circle(frame, (x, y), r, (0, 255, 0), 2)  # Circle
                cv2.circle(frame, (x, y), 5, (255, 0, 0), -1)  # Centroid
                cv2.putText(frame, f"x={x_mm:.2f} mm, y={y_mm:.2f} mm, r={r_mm:.2f} mm, z={z_mm:.2f} mm",
                            (x - 50, y - r - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

            # Update last detected circles
            last_detected = circles

        # Display the frame with detected circles
        cv2.imshow("USB Webcam Circle Detection", frame)

        # Break loop on 'q' key press
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

        # Wait for the next frame interval
        time_elapsed = time.time() - start_time
        time.sleep(max(0, fps_interval - time_elapsed))

    # Write stationary object details to a text file
    with open("data.txt", "w") as file:
        file.write("\n".join(stationary_objects))
        print("Stationary object details exported to data.txt")

    cap.release()
    cv2.destroyAllWindows()

# Run the USB webcam processing function
# Use the correct camera index from Device Manager (e.g., 0, 1, 2, etc.)
process_usb_webcam_for_circles(camera_index=0)

import cv2
import numpy as np
import time
import socket

# Server Configuration
SERVER_HOST = '192.168.1.250'  # Replace with your server IP
SERVER_PORT = 8080             # Replace with your server port

# Define pixel-to-mm scale
mm_per_pixel = 0.1  # Example: 1 pixel = 0.1 mm

def process_usb_webcam_for_circles(camera_index=0, fps_interval=5):
    """
    Process USB webcam input to detect circles and output their centroids, radii, and depth.
    Sends stationary object coordinates via TCP/IP.
    """
    # Open the USB webcam using the specified camera index (port from device manager)
    cap = cv2.VideoCapture(camera_index, cv2.CAP_DSHOW)
    if not cap.isOpened():
        print(f"Error: Could not access the webcam on port {camera_index}.")
        return

    stationary_objects = []  # To store stationary x, y, z, and radius values
    last_detected = None  # Store the previous frame's detected circles
    last_written_location = None  # Track the last sent constant location

    print("Press 'q' to quit.")

    # Setup TCP/IP client socket
    try:
        client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        client_socket.connect((SERVER_HOST, SERVER_PORT))
        print(f"Connected to server at {SERVER_HOST}:{SERVER_PORT}")
    except Exception as e:
        print(f"Error: Unable to connect to server. {e}")
        return

    while True:
        try:
            start_time = time.time()
            ret, frame = cap.read()
            if not ret:
                print("Error: Could not read frame from the webcam.")
                break

            # Convert frame to grayscale
            gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

            # Apply Gaussian Blur to reduce noise
            blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

            # Detect circles using Hough Circle Transform
            circles = cv2.HoughCircles(
                blurred_frame,
                cv2.HOUGH_GRADIENT,
                dp=1.2,  # Inverse ratio of the accumulator resolution to the image resolution
                minDist=50,  # Minimum distance between circle centers
                param1=50,  # Upper threshold for Canny edge detection
                param2=30,  # Threshold for center detection
                minRadius=10,  # Minimum circle radius
                maxRadius=100  # Maximum circle radius
            )

            if circles is not None:
                circles = np.round(circles[0, :]).astype("int")  # Round and convert to integer
                for (x, y, r) in circles:
                    # Convert coordinates and radius to millimeters
                    x_mm = x * mm_per_pixel
                    y_mm = y * mm_per_pixel
                    r_mm = r * mm_per_pixel
                    z_mm = 75  # Set z to 75 mm for stationary objects

                    # Check if the object is stationary (detected in two consecutive frames)
                    if last_detected is not None:
                        for (prev_x, prev_y, prev_r) in last_detected:
                            if abs(prev_x - x) < 5 and abs(prev_y - y) < 5 and abs(prev_r - r) < 5:
                                # Object considered stationary
                                location_line = f"x={x_mm:.2f}, y={y_mm:.2f}, z={z_mm:.2f}, radius={r_mm:.2f}"
                                if location_line != last_written_location:  # Only send if location is different
                                    stationary_objects.append(location_line)
                                    last_written_location = location_line  # Update the last written location
                                    # Send the location to the server
                                    client_socket.sendall(location_line.encode('utf-8'))
                                    print(f"Sent: {location_line}")

                    # Draw the circle and centroid on the frame
                    cv2.circle(frame, (x, y), r, (0, 255, 0), 2)  # Circle
                    cv2.circle(frame, (x, y), 5, (255, 0, 0), -1)  # Centroid
                    cv2.putText(frame, f"x={x_mm:.2f} mm, y={y_mm:.2f} mm, r={r_mm:.2f} mm, z={z_mm:.2f} mm",
                                (x - 50, y - r - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

                # Update last detected circles
                last_detected = circles

            # Display the frame with detected circles
            cv2.imshow("USB Webcam Circle Detection", frame)

            # Break loop on 'q' key press
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

            # Wait for the next frame interval
            time_elapsed = time.time() - start_time
            time.sleep(max(0, fps_interval - time_elapsed))

        except Exception as e:
            print(f"Error: {e}")
            break

    cap.release()
    client_socket.close()
    cv2.destroyAllWindows()
    print("Connection closed.")

# Run the USB webcam processing function
# Use the correct camera index from Device Manager (e.g., 0, 1, 2, etc.)
process_usb_webcam_for_circles(camera_index=0)

#20241204 11:20 AM
import cv2
import numpy as np
import time
import socket

# Server Configuration
SERVER_HOST = '192.168.1.250'  # Replace with your server IP
SERVER_PORT = 8080             # Replace with your server port

# Define pixel-to-mm scale
mm_per_pixel = 0.1  # Example: 1 pixel = 0.1 mm


def process_usb_webcam_for_circles(camera_index=0, fps_interval=5):
    """
    Process USB webcam input to detect circles and output their numbered centroids, radii, and depth.
    Returns stationary objects as a dictionary.
    """
    cap = cv2.VideoCapture(camera_index, cv2.CAP_DSHOW)
    if not cap.isOpened():
        print(f"Error: Could not access the webcam on port {camera_index}.")
        return {}

    stationary_objects = {}  # To store object ID and its properties
    last_detected = {}  # Store previously detected object centroids
    next_id = 1  # To assign unique IDs to new objects

    print("Press 'q' to quit.")

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Error: Could not read frame from the webcam.")
            break

        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

        # Detect circles using Hough Circle Transform
        circles = cv2.HoughCircles(
            blurred_frame,
            cv2.HOUGH_GRADIENT,
            dp=1.2,
            minDist=50,
            param1=50,
            param2=30,
            minRadius=10,
            maxRadius=100
        )

        current_frame_objects = {}

        if circles is not None:
            circles = np.round(circles[0, :]).astype("int")
            for (x, y, r) in circles:
                x_mm = x * mm_per_pixel
                y_mm = y * mm_per_pixel
                r_mm = r * mm_per_pixel
                z_mm = 75  # Set z to 75 mm for stationary objects

                # Try to match the circle to an existing object by centroid
                matched_id = None
                for obj_id, (prev_x, prev_y, _) in last_detected.items():
                    if abs(prev_x - x) < 5 and abs(prev_y - y) < 5:  # Centroid proximity threshold
                        matched_id = obj_id
                        break

                if matched_id is None:
                    # Assign a new ID if no match is found
                    matched_id = next_id
                    next_id += 1

                current_frame_objects[matched_id] = (x, y, r)
                stationary_objects[matched_id] = (x_mm, y_mm, r_mm, z_mm)

                # Draw the circle and ID on the frame
                cv2.circle(frame, (x, y), r, (0, 255, 0), 2)  # Circle
                cv2.circle(frame, (x, y), 5, (255, 0, 0), -1)  # Centroid
                cv2.putText(frame, f"ID={matched_id}, x={x_mm:.2f}, y={y_mm:.2f}, r={r_mm:.2f}, z={z_mm:.2f}",
                            (x - 50, y - r - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

        # Update last_detected with current_frame_objects
        last_detected = {obj_id: (x, y, r) for obj_id, (x, y, r) in current_frame_objects.items()}

        cv2.imshow("USB Webcam Circle Detection", frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

        time.sleep(fps_interval)

    cap.release()
    cv2.destroyAllWindows()
    return stationary_objects


def file_output(stationary_objects, filename="data.txt"):
    """
    Outputs stationary objects to a file.
    """
    try:
        with open(filename, "w") as file:
            for obj_id, (x, y, r, z) in stationary_objects.items():
                file.write(f"ID={obj_id}, x={x:.2f}, y={y:.2f}, r={r:.2f}, z={z:.2f}\n")
        print(f"Stationary object details exported to {filename}")
    except Exception as e:
        print(f"Error writing to file: {e}")


def tcpip_output(stationary_objects):
    """
    Sends stationary object details to a TCP/IP server.
    """
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
            client_socket.connect((SERVER_HOST, SERVER_PORT))
            print(f"Connected to server at {SERVER_HOST}:{SERVER_PORT}")

            for obj_id, (x, y, r, z) in stationary_objects.items():
                message = f"ID={obj_id}, x={x:.2f}, y={y:.2f}, r={r:.2f}, z={z:.2f}"
                client_socket.sendall(message.encode('utf-8'))
                print(f"Sent: {message}")
    except Exception as e:
        print(f"Error with TCP/IP communication: {e}")


# Main Execution
if __name__ == "__main__":
    stationary_objects = process_usb_webcam_for_circles(camera_index=0, fps_interval=5)
    if stationary_objects:
        # Optional: File output
        file_output(stationary_objects)

        # TCP/IP output
        tcpip_output(stationary_objects)

import cv2
import numpy as np
import time
import socket

# Server Configuration
SERVER_HOST = '192.168.1.250'  # Replace with your server IP
SERVER_PORT = 8080             # Replace with your server port

# Define pixel-to-mm scale
mm_per_pixel = 0.1  # Example: 1 pixel = 0.1 mm


def process_usb_webcam_for_circles(camera_index=0, fps_interval=5):
    """
    Process USB webcam input to detect circles and output their numbered centroids, radii, and depth.
    Returns stationary objects as a dictionary.
    """
    cap = cv2.VideoCapture(camera_index, cv2.CAP_DSHOW)
    if not cap.isOpened():
        print(f"Error: Could not access the webcam on port {camera_index}.")
        return {}

    stationary_objects = {}  # To store object ID and its properties
    last_detected = {}  # Store previously detected object centroids
    next_id = 1  # To assign unique IDs to new objects

    print("Press 'q' to quit.")

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Error: Could not read frame from the webcam.")
            break

        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

        # Detect circles using Hough Circle Transform
        circles = cv2.HoughCircles(
            blurred_frame,
            cv2.HOUGH_GRADIENT,
            dp=1.2,
            minDist=50,
            param1=50,
            param2=30,
            minRadius=10,
            maxRadius=100
        )

        current_frame_objects = {}

        if circles is not None:
            circles = np.round(circles[0, :]).astype("int")
            for (x, y, r) in circles:
                x_mm = x * mm_per_pixel
                y_mm = y * mm_per_pixel
                r_mm = r * mm_per_pixel
                z_mm = 75  # Set z to 75 mm for stationary objects

                # Try to match the circle to an existing object by centroid
                matched_id = None
                for obj_id, (prev_x, prev_y, _) in last_detected.items():
                    if abs(prev_x - x) < 5 and abs(prev_y - y) < 5:  # Centroid proximity threshold
                        matched_id = obj_id
                        break

                if matched_id is None:
                    # Assign a new ID if no match is found
                    matched_id = next_id
                    next_id += 1

                current_frame_objects[matched_id] = (x, y, r)
                stationary_objects[matched_id] = (x_mm, y_mm, r_mm, z_mm)

                # Draw the circle and ID on the frame
                cv2.circle(frame, (x, y), r, (0, 255, 0), 2)  # Circle
                cv2.circle(frame, (x, y), 5, (255, 0, 0), -1)  # Centroid
                cv2.putText(frame, f"ID={matched_id}, x={x_mm:.2f}, y={y_mm:.2f}, r={r_mm:.2f}, z={z_mm:.2f}",
                            (x - 50, y - r - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

        # Update last_detected with current_frame_objects
        last_detected = {obj_id: (x, y, r) for obj_id, (x, y, r) in current_frame_objects.items()}

        cv2.imshow("USB Webcam Circle Detection", frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

        time.sleep(fps_interval)

    cap.release()
    cv2.destroyAllWindows()
    return stationary_objects


def file_output(stationary_objects, filename="data.txt"):
    """
    Outputs stationary objects to a file.
    """
    try:
        with open(filename, "w") as file:
            for obj_id, (x, y, r, z) in stationary_objects.items():
                file.write(f"ID={obj_id}, x={x:.2f}, y={y:.2f}, r={r:.2f}, z={z:.2f}\n")
        print(f"Stationary object details exported to {filename}")
    except Exception as e:
        print(f"Error writing to file: {e}")


def tcpip_output(stationary_objects):
    """
    Sends stationary object details to a TCP/IP server and prints them.
    """
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
            client_socket.connect((SERVER_HOST, SERVER_PORT))
            print(f"Connected to server at {SERVER_HOST}:{SERVER_PORT}")

            for obj_id, (x, y, r, z) in stationary_objects.items():
                message = f"ID={obj_id}, x={x:.2f}, y={y:.2f}, r={r:.2f}, z={z:.2f}"
                client_socket.sendall(message.encode('utf-8'))
                print(f"Sent: {message}")
    except Exception as e:
        print(f"Error with TCP/IP communication: {e}")


# Main Execution
if __name__ == "__main__":
    stationary_objects = process_usb_webcam_for_circles(camera_index=0, fps_interval=5)
    if stationary_objects:
        # Print and TCP/IP output
        tcpip_output(stationary_objects)

        # Optional: File output
        file_output(stationary_objects)

#working code with print output
import cv2
import numpy as np
import time
import socket

# Server Configuration
SERVER_HOST = '192.168.1.250'  # Replace with your server IP
SERVER_PORT = 8080             # Replace with your server port

# Define pixel-to-mm scale
mm_per_pixel = 0.1  # Example: 1 pixel = 0.1 mm

def process_usb_webcam_for_circles(camera_index=0, fps_interval=5):
    """
    Process USB webcam input to detect circles and output their centroids, radii, and depth.
    Returns stationary objects as a list of strings.
    """
    cap = cv2.VideoCapture(camera_index, cv2.CAP_DSHOW)
    if not cap.isOpened():
        print(f"Error: Could not access the webcam on port {camera_index}.")
        return []

    stationary_objects = []  # To store stationary x, y, z, and radius values
    last_detected = None  # Store the previous frame's detected circles
    last_written_location = None  # Track the last sent location

    print("Press 'q' to quit.")

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Error: Could not read frame from the webcam.")
            break

        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

        # Detect circles using Hough Circle Transform
        circles = cv2.HoughCircles(
            blurred_frame,
            cv2.HOUGH_GRADIENT,
            dp=1.2,
            minDist=50,
            param1=50,
            param2=30,
            minRadius=10,
            maxRadius=100
        )

        if circles is not None:
            circles = np.round(circles[0, :]).astype("int")
            for (x, y, r) in circles:
                x_mm = x * mm_per_pixel
                y_mm = y * mm_per_pixel
                r_mm = r * mm_per_pixel
                z_mm = 75  # Set z to 75 mm for stationary objects

                if last_detected is not None:
                    for (prev_x, prev_y, prev_r) in last_detected:
                        if abs(prev_x - x) < 5 and abs(prev_y - y) < 5 and abs(prev_r - r) < 5:
                            location_line = f"x={x_mm:.2f}, y={y_mm:.2f}, z={z_mm:.2f}, radius={r_mm:.2f}"
                            if location_line != last_written_location:
                                stationary_objects.append(location_line)
                                last_written_location = location_line
                                print(f"Stationary Object: {location_line}")

                cv2.circle(frame, (x, y), r, (0, 255, 0), 2)
                cv2.circle(frame, (x, y), 5, (255, 0, 0), -1)
                cv2.putText(frame, f"x={x_mm:.2f}, y={y_mm:.2f}, r={r_mm:.2f}, z={z_mm:.2f}",
                            (x - 50, y - r - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

            last_detected = circles

        cv2.imshow("USB Webcam Circle Detection", frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

        time.sleep(fps_interval)

    cap.release()
    cv2.destroyAllWindows()
    return stationary_objects


def file_output(stationary_objects, filename="data.txt"):
    """
    Outputs stationary objects to a file.
    """
    try:
        with open(filename, "w") as file:
            file.write("\n".join(stationary_objects))
        print(f"Stationary object details exported to {filename}")
    except Exception as e:
        print(f"Error writing to file: {e}")


def tcpip_output(stationary_objects):
    """
    Sends stationary object details to a TCP/IP server.
    """
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
            client_socket.connect((SERVER_HOST, SERVER_PORT))
            print(f"Connected to server at {SERVER_HOST}:{SERVER_PORT}")

            for location_line in stationary_objects:
                client_socket.sendall(location_line.encode('utf-8'))
                print(f"Sent: {location_line}")
    except Exception as e:
        print(f"Error with TCP/IP communication: {e}")


# Main Execution
if __name__ == "__main__":
    stationary_objects = process_usb_webcam_for_circles(camera_index=0, fps_interval=5)
    if stationary_objects:
        # Optional: File output
        file_output(stationary_objects)

        # TCP/IP output
        tcpip_output(stationary_objects)

# Note: Only the modifications requested have been made.
# Everything else in the original code remains unchanged except where specified.
# Pre ID but everything else PCPIP Good

import cv2
import numpy as np
import time
import socket

# Server Configuration
SERVER_HOST = '192.168.1.250'  # Replace with your server IP
SERVER_PORT = 8080             # Replace with your server port

# Define pixel-to-mm scale
mm_per_pixel = 0.42  # Example: 1 pixel = 0.1 mm

def process_usb_webcam_for_circles(camera_index=0, fps_interval=5):
    """
    Process USB webcam input to detect circles and output their centroids, radii, and depth.
    Only outputs when all circles detected are stable between frames.
    Only detects circles with diameters between 30–50 mm (hence radius 15–25 mm).
    Outputs results in # # # # format (x y z r).
    """
    cap = cv2.VideoCapture(camera_index, cv2.CAP_DSHOW)
    if not cap.isOpened():
        print(f"Error: Could not access the webcam on port {camera_index}.")
        return []

    stationary_objects = []  # To store stationary x, y, z, and radius values
    last_detected = None  # Store the previous frame's detected circles
    last_written_location = None  # Track the last sent location

    print("Press 'q' to quit.")

    # Convert desired mm diameters to pixel radius
    # Diameter: 30–50 mm => Radius: 15–25 mm
    # With mm_per_pixel = 0.1 mm/pixel => radius in pixels = radius_mm / mm_per_pixel
    min_radius_pixels = int(15 / mm_per_pixel)  # 15 mm / 0.1 mm/pixel = 150 pixels
    max_radius_pixels = int(25 / mm_per_pixel)  # 25 mm / 0.1 mm/pixel = 250 pixels

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Error: Could not read frame from the webcam.")
            break

        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

        # Detect circles using Hough Circle Transform with the new radius constraints
        circles = cv2.HoughCircles(
            blurred_frame,
            cv2.HOUGH_GRADIENT,
            dp=1.2,
            minDist=50,
            param1=50,
            param2=30,
            minRadius=min_radius_pixels,
            maxRadius=max_radius_pixels
        )

        if circles is not None:
            circles = np.round(circles[0, :]).astype("int")

            # If we have a previous detection, check stability
            if last_detected is not None:
                # Check if all current circles have a close match in last_detected
                all_stable = True
                current_locations = []

                for (x, y, r) in circles:
                    # Find a matching circle from last_detected
                    stable_match_found = False
                    for (prev_x, prev_y, prev_r) in last_detected:
                        if abs(prev_x - x) < 5 and abs(prev_y - y) < 5 and abs(prev_r - r) < 5:
                            # We found a stable match for this circle
                            stable_match_found = True
                            break
                    if not stable_match_found:
                        all_stable = False
                        break
                    else:
                        # Compute mm values for output
                        x_mm = x * mm_per_pixel
                        y_mm = y * mm_per_pixel
                        r_mm = r * mm_per_pixel
                        z_mm = 75  # Set z to 75 mm for stationary objects
                        current_locations.append((x_mm, y_mm, z_mm, r_mm))

                # Only print if ALL circles are stable
                if all_stable and current_locations:
                    # Format output as numbers: "x y z r"
                    # If multiple circles, print each one on a new line
                    output_lines = []
                    for (x_mm, y_mm, z_mm, r_mm) in current_locations:
                        line = f"{x_mm:.2f} {y_mm:.2f} {z_mm:.2f} {r_mm:.2f}"
                        output_lines.append(line)
                    output_str = "\n".join(output_lines)

                    # Check if this output differs from last written to avoid duplicates
                    if output_str != last_written_location:
                        stationary_objects.append(output_str)
                        last_written_location = output_str
                        print(output_str)

            # Draw the detected circles for visualization (unchanged logic)
            for (x, y, r) in circles:
                x_mm = x * mm_per_pixel
                y_mm = y * mm_per_pixel
                r_mm = r * mm_per_pixel
                z_mm = 75
                cv2.circle(frame, (x, y), r, (0, 255, 0), 2)
                cv2.circle(frame, (x, y), 5, (255, 0, 0), -1)
                cv2.putText(frame, f"{x_mm:.2f} {y_mm:.2f} {z_mm:.2f} {r_mm:.2f}",
                            (x - 50, y - r - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

            last_detected = circles

        cv2.imshow("USB Webcam Circle Detection", frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

        time.sleep(fps_interval)

    cap.release()
    cv2.destroyAllWindows()
    return stationary_objects


def file_output(stationary_objects, filename="data.txt"):
    """
    Outputs stationary objects to a file.
    """
    try:
        with open(filename, "w") as file:
            file.write("\n".join(stationary_objects))
        print(f"Stationary object details exported to {filename}")
    except Exception as e:
        print(f"Error writing to file: {e}")


def tcpip_output(stationary_objects):
    """
    Sends stationary object details to a TCP/IP server.
    """
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
            client_socket.connect((SERVER_HOST, SERVER_PORT))
            print(f"Connected to server at {SERVER_HOST}:{SERVER_PORT}")

            for location_line in stationary_objects:
                client_socket.sendall(location_line.encode('utf-8'))
                print(f"Sent: {location_line}")
    except Exception as e:
        print(f"Error with TCP/IP communication: {e}")


# Main Execution
if __name__ == "__main__":
    stationary_objects = process_usb_webcam_for_circles(camera_index=0, fps_interval=5)
    if stationary_objects:
        # Optional: File output
        file_output(stationary_objects)

        # TCP/IP output
        tcpip_output(stationary_objects)

# Note: This code builds on the previous modified version.
# Changes:
# 1. Assign a unique ID to each object detected.
# 2. Maintain the same ID for the same object even as it moves.
# 3. Output format: ID# x y z r (e.g., "ID1 100.00 200.00 75.00 20.00")
# 4. Still only print/output when all currently detected circles are stable.
# 5. Maintain ID assignment even if other objects are removed.
#
# The logic:
# - Keep a dictionary of objects keyed by ID.
# - Each entry stores last known position and radius.
# - On each stable detection, match each detected circle to an existing object by nearest match.
# - If no match is found, create a new ID.
# - Update positions as objects move, retaining the same ID.
# - Only print when all are stable (as before).

import cv2
import numpy as np
import time
import socket

# Server Configuration
SERVER_HOST = '192.168.1.250'  # Replace with your server IP
SERVER_PORT = 8080             # Replace with your server port

# Define pixel-to-mm scale
mm_per_pixel = 0.42  # Example: 1 pixel = 0.1 mm

def assign_ids_to_objects(objects_dict, detected_circles, id_next):
    """
    Assign IDs to the currently detected circles based on nearest match to existing objects.
    objects_dict: {id: {'x': x_mm, 'y': y_mm, 'r': r_mm, 'z': z_mm}}
    detected_circles: list of (x, y, r) in pixels
    id_next: the next ID number available if we need a new ID

    Returns: updated_objects_dict, updated_id_next
    """
    # Convert detected circles to mm
    detected_mm = []
    for (x, y, r) in detected_circles:
        x_mm = x * mm_per_pixel
        y_mm = y * mm_per_pixel
        r_mm = r * mm_per_pixel
        z_mm = 75  # fixed
        detected_mm.append((x_mm, y_mm, z_mm, r_mm))

    # If no existing objects, assign new IDs to all
    if not objects_dict:
        for circle in detected_mm:
            objects_dict[f"ID{id_next}"] = {'x': circle[0], 'y': circle[1], 'z': circle[2], 'r': circle[3]}
            id_next += 1
        return objects_dict, id_next

    # Otherwise, we attempt to match each detected object to an existing one
    unmatched_detections = detected_mm[:]
    updated_dict = {}

    # We'll use a greedy nearest-neighbor matching approach.
    # For each existing object, find the nearest detected circle.
    # Then remove that detected circle from the unmatched list.
    existing_ids = list(objects_dict.keys())

    # Attempt to match existing objects first
    for obj_id in existing_ids:
        obj_x = objects_dict[obj_id]['x']
        obj_y = objects_dict[obj_id]['y']
        obj_r = objects_dict[obj_id]['r']

        # Find closest match by Euclidean distance in (x,y,r) space
        # Although radius might not be as crucial for matching, we can still include it.
        # Primarily x,y should be enough for stable match, but we keep radius check minimal.
        best_match = None
        best_dist = float('inf')
        for (d_x, d_y, d_z, d_r) in unmatched_detections:
            dist = np.sqrt((d_x - obj_x)**2 + (d_y - obj_y)**2 + (d_r - obj_r)**2)
            if dist < best_dist:
                best_dist = dist
                best_match = (d_x, d_y, d_z, d_r)

        if best_match is not None:
            # Update the object with the matched detection
            updated_dict[obj_id] = {'x': best_match[0], 'y': best_match[1], 'z': best_match[2], 'r': best_match[3]}
            unmatched_detections.remove(best_match)

    # Now, assign new IDs to any unmatched detections
    for (d_x, d_y, d_z, d_r) in unmatched_detections:
        updated_dict[f"ID{id_next}"] = {'x': d_x, 'y': d_y, 'z': d_z, 'r': d_r}
        id_next += 1

    return updated_dict, id_next

def process_usb_webcam_for_circles(camera_index=0, fps_interval=5):
    """
    Process USB webcam input to detect circles and output their centroids, radii, and depth.
    Only outputs when all circles detected are stable between frames.
    Only detects circles with diameters between 30–50 mm (hence radius 15–25 mm).
    Outputs results in "ID# x y z r" format.
    Maintains IDs for each detected object even as they move or others disappear.
    """

    cap = cv2.VideoCapture(camera_index, cv2.CAP_DSHOW)
    if not cap.isOpened():
        print(f"Error: Could not access the webcam on port {camera_index}.")
        return []

    stationary_objects = []  # To store stationary x, y, z, r lines (with IDs)
    last_detected = None  # Store previous frame's detected circles (pixels)
    last_written_location = None  # Track last output lines

    # For ID assignment and tracking
    objects_dict = {}  # {id_str: {'x': x_mm, 'y': y_mm, 'z': z_mm, 'r': r_mm}}
    id_next = 1

    print("Press 'q' to quit.")

    # Convert desired mm diameters to pixel radius
    # Diameter: 30–50 mm => Radius: 15–25 mm
    # With mm_per_pixel = 0.1 mm/pixel => radius in pixels = radius_mm / mm_per_pixel
    min_radius_pixels = int(15 / mm_per_pixel)  # 15 mm / 0.1 mm/pixel = 150 pixels
    max_radius_pixels = int(25 / mm_per_pixel)  # 25 mm / 0.1 mm/pixel = 250 pixels

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Error: Could not read frame from the webcam.")
            break

        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

        # Detect circles using Hough Circle Transform with the new radius constraints
        circles = cv2.HoughCircles(
            blurred_frame,
            cv2.HOUGH_GRADIENT,
            dp=1.2,
            minDist=50,
            param1=50,
            param2=30,
            minRadius=min_radius_pixels,
            maxRadius=max_radius_pixels
        )

        if circles is not None:
            circles = np.round(circles[0, :]).astype("int")

            # If we have a previous detection, check stability
            if last_detected is not None:
                # Check if all current circles have a close match in last_detected
                all_stable = True
                # For stability, each circle in current must match a previous circle
                for (x, y, r) in circles:
                    stable_match_found = False
                    for (prev_x, prev_y, prev_r) in last_detected:
                        if abs(prev_x - x) < 5 and abs(prev_y - y) < 5 and abs(prev_r - r) < 5:
                            stable_match_found = True
                            break
                    if not stable_match_found:
                        all_stable = False
                        break

                # If stable, assign/update IDs and print output
                if all_stable:
                    # Assign IDs based on objects_dict
                    objects_dict, id_next = assign_ids_to_objects(objects_dict, circles, id_next)
                    # Prepare output lines
                    output_lines = []
                    for obj_id, vals in objects_dict.items():
                        x_mm = vals['x']
                        y_mm = vals['y']
                        z_mm = vals['z']
                        r_mm = vals['r']
                        line = f"{obj_id} {x_mm:.2f} {y_mm:.2f} {z_mm:.2f} {r_mm:.2f}"
                        output_lines.append(line)
                    output_str = "\n".join(output_lines)

                    if output_str != last_written_location:
                        stationary_objects.append(output_str)
                        last_written_location = output_str
                        print(output_str)

            # Draw the detected circles for visualization
            for (x, y, r) in circles:
                x_mm = x * mm_per_pixel
                y_mm = y * mm_per_pixel
                r_mm = r * mm_per_pixel
                z_mm = 75
                cv2.circle(frame, (x, y), r, (0, 255, 0), 2)
                cv2.circle(frame, (x, y), 5, (255, 0, 0), -1)
                cv2.putText(frame, f"{x_mm:.2f} {y_mm:.2f} {z_mm:.2f} {r_mm:.2f}",
                            (x - 50, y - r - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

            last_detected = circles
        else:
            # If no circles are detected, we do not print or alter IDs.
            # Objects remain in dictionary but won't output since not stable currently.
            pass

        cv2.imshow("USB Webcam Circle Detection", frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

        time.sleep(fps_interval)

    cap.release()
    cv2.destroyAllWindows()
    return stationary_objects


def file_output(stationary_objects, filename="data.txt"):
    """
    Outputs stationary objects to a file.
    """
    try:
        with open(filename, "w") as file:
            file.write("\n".join(stationary_objects))
        print(f"Stationary object details exported to {filename}")
    except Exception as e:
        print(f"Error writing to file: {e}")


def tcpip_output(stationary_objects):
    """
    Sends stationary object details to a TCP/IP server.
    """
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
            client_socket.connect((SERVER_HOST, SERVER_PORT))
            print(f"Connected to server at {SERVER_HOST}:{SERVER_PORT}")

            for location_line in stationary_objects:
                client_socket.sendall(location_line.encode('utf-8'))
                print(f"Sent: {location_line}")
    except Exception as e:
        print(f"Error with TCP/IP communication: {e}")


# Main Execution
if __name__ == "__main__":
    stationary_objects = process_usb_webcam_for_circles(camera_index=0, fps_interval=5)
    if stationary_objects:
        # Optional: File output
        file_output(stationary_objects)

        # TCP/IP output
        tcpip_output(stationary_objects)

#CORRECT CODE 20241205

import cv2
import numpy as np
import time
import socket

# Server Configuration
SERVER_HOST = '192.168.1.250'  # Replace with your server IP
SERVER_PORT = 8080             # Replace with your server port

# Define pixel-to-mm scale
mm_per_pixel = 0.42

def assign_ids_to_objects(objects_dict, detected_circles, id_next, last_visible_ids):
    detected_mm = []
    for (x, y, r) in detected_circles:
        x_mm = x * mm_per_pixel
        y_mm = y * mm_per_pixel
        r_mm = r * mm_per_pixel
        z_mm = 75  # fixed depth
        detected_mm.append((x_mm, y_mm, z_mm, r_mm))

    unmatched_detections = detected_mm[:]
    updated_dict = {}
    current_visible_ids = set()

 # First, try to match with previously visible objects
    for obj_id in last_visible_ids:
        if obj_id in objects_dict:
            obj_x = objects_dict[obj_id]['x']
            obj_y = objects_dict[obj_id]['y']
            obj_r = objects_dict[obj_id]['r']

            best_match = None
            best_dist = float('inf')
            for (d_x, d_y, d_z, d_r) in unmatched_detections:
                dist = np.sqrt((d_x - obj_x)**2 + (d_y - obj_y)**2 + (d_r - obj_r)**2)
                if dist < best_dist:
                    best_dist = dist
                    best_match = (d_x, d_y, d_z, d_r)

            if best_match is not None and best_dist < 20:  # Add a threshold for matching
                updated_dict[obj_id] = {'x': best_match[0], 'y': best_match[1], 'z': best_match[2], 'r': best_match[3]}
                objects_dict[obj_id] = updated_dict[obj_id]
                current_visible_ids.add(obj_id)
                unmatched_detections.remove(best_match)

    # Assign new IDs to any unmatched detections
    for (d_x, d_y, d_z, d_r) in unmatched_detections:
        new_id = f"ID{id_next}"
        updated_dict[new_id] = {'x': d_x, 'y': d_y, 'z': d_z, 'r': d_r}
        objects_dict[new_id] = updated_dict[new_id]
        current_visible_ids.add(new_id)
        id_next += 1

    return updated_dict, objects_dict, id_next, current_visible_ids

    # Note: Objects that were previously visible but not matched now are simply not in updated_dict.
    # They remain in objects_dict but will not appear in future matches since we only match last_visible_ids.
    # This ensures no ID re-use or "stealing" of IDs by new objects.

    return updated_dict, objects_dict, id_next, current_visible_ids

def process_usb_webcam_for_circles(camera_index=0, fps_interval=2, id_next=1):
    """
    Process USB webcam input to detect circles and output their centroids, radii, and depth.
    Key features:
    - Only outputs when all currently detected circles are stable between frames.
    - Detects circles with diameters between 30–50 mm => radius 15–25 mm.
    - Outputs "ID# x y z r" format.
    - Maintains unique IDs for each detected object without reuse.
    - If an object disappears, the remaining objects keep their IDs.
    - If a new object appears later, it gets a new ID (e.g., ID3) without reusing IDs of disappeared objects.
    """

    cap = cv2.VideoCapture(camera_index, cv2.CAP_DSHOW)
    if not cap.isOpened():
        print(f"Error: Could not access the webcam on port {camera_index}.")
        return []

    stationary_objects = []
    last_detected = None
    last_written_location = None

    # For ID assignment and tracking
    objects_dict = {}
    id_next = 1
    last_visible_ids = set()  # IDs visible in the previous stable detection

    print("Press 'q' to quit.")

    # Determine pixel radius constraints based on mm
    min_radius_pixels = int(15 / mm_per_pixel)
    max_radius_pixels = int(25 / mm_per_pixel)
    min_radius_pixels = max(min_radius_pixels, 1)
    max_radius_pixels = max(max_radius_pixels, min_radius_pixels + 1)

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Error: Could not read frame from the webcam.")
            break

        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        blurred_frame = cv2.GaussianBlur(gray_frame, (9, 9), 2)

        circles = cv2.HoughCircles(
            blurred_frame,
            cv2.HOUGH_GRADIENT,
            dp=1.2,
            minDist=50,
            param1=50,
            param2=30,
            minRadius=min_radius_pixels,
            maxRadius=max_radius_pixels
        )

        if circles is not None:
            circles = np.round(circles[0, :]).astype("int")

            if last_detected is not None:
                # Check stability
                all_stable = True
                for (x, y, r) in circles:
                    stable_match_found = False
                    for (prev_x, prev_y, prev_r) in last_detected:
                        if abs(prev_x - x) < 5 and abs(prev_y - y) < 5 and abs(prev_r - r) < 5:
                            stable_match_found = True
                            break
                    if not stable_match_found:
                        all_stable = False
                        break

                # If stable, assign/update IDs
                if all_stable:
                    updated_dict, objects_dict, id_next, current_visible_ids = assign_ids_to_objects(
                      objects_dict, circles, id_next, last_visible_ids
                    )
                    # Prepare output lines for currently visible stable objects
                    output_lines = []
                    for obj_id, vals in updated_dict.items():
                        x_mm = vals['x']
                        y_mm = vals['y']
                        z_mm = vals['z']
                        r_mm = vals['r']
                        line = f"{obj_id} {x_mm:.2f} {y_mm:.2f} {z_mm:.2f} {r_mm:.2f}"
                        output_lines.append(line)
                    output_str = "\n".join(output_lines)

                    if output_str != last_written_location:
                        stationary_objects.append(output_str)
                        last_written_location = output_str
                        print(output_str)

                    # Update last_visible_ids for next stable detection
                    last_visible_ids = current_visible_ids
            else:
                # First stable detection requires establishing stability
                # Without a previous frame, we can't confirm stability yet.
                last_visible_ids = set()

            # Draw circles
            for (x, y, r) in circles:
                x_mm = x * mm_per_pixel
                y_mm = y * mm_per_pixel
                r_mm = r * mm_per_pixel
                z_mm = 75
                cv2.circle(frame, (x, y), r, (0, 255, 0), 2)
                cv2.circle(frame, (x, y), 5, (255, 0, 0), -1)
                cv2.putText(frame, f"{x_mm:.2f} {y_mm:.2f} {z_mm:.2f} {r_mm:.2f}",
                            (x - 50, y - r - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

            last_detected = circles
        else:
            # No circles detected: no stability check, no reassignments
            # Clear last_visible_ids since no objects are visible now
            last_visible_ids = set()

        cv2.imshow("USB Webcam Circle Detection", frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

        time.sleep(fps_interval)

    cap.release()
    cv2.destroyAllWindows()
    return stationary_objects
    return stationary_objects, id_next


def file_output(stationary_objects, filename="data.txt"):
    """
    Outputs stationary objects to a file.
    """
    try:
        with open(filename, "w") as file:
            file.write("\n".join(stationary_objects))
        print(f"Stationary object details exported to {filename}")
    except Exception as e:
        print(f"Error writing to file: {e}")


def tcpip_output(stationary_objects):
    """
    Sends stationary object details to a TCP/IP server.
    """
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
            client_socket.connect((SERVER_HOST, SERVER_PORT))
            print(f"Connected to server at {SERVER_HOST}:{SERVER_PORT}")

            for location_line in stationary_objects:
                client_socket.sendall(location_line.encode('utf-8'))
                print(f"Sent: {location_line}")
    except Exception as e:
        print(f"Error with TCP/IP communication: {e}")


if __name__ == "__main__":
    id_next = 1
    stationary_objects, id_next = process_usb_webcam_for_circles(camera_index=0, fps_interval=2, id_next=id_next)
    if stationary_objects:
        file_output(stationary_objects)
        tcpip_output(stationary_objects)